# Site settings
title: pandalin
header-img: "img/autumn2.jpg"
tagline: "pandalin"
description: "人所缺乏的不是才干而是志向，不是成功的能力而是勤劳的意志。"
baseurl: ""
url: ""
#url: "http://localhost:4000"

# About/contact
owner:
  name: "pandalin"
  email: ascendlin@sina.com
  bio: "君子志于择天下"

# Data
gavatar: http://dreamofbook.qiniudn.com/pandalin.png
favicon: img/favicon.ico

twitter_username: ascendlin
github_username: pandalin
facebook_username: pandalin

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "pandalin"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : pandalin
  disqus :
      short_name : pandalin

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
